version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: orcaeventos-app
    container_name: orcaeventos-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    environment:
      - DB_HOST=db
      - DB_DATABASE=orcaeventos
      - DB_USERNAME=orca
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mariadb:11.3
    container_name: orcaeventos-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: orcaeventos
      MARIADB_USER: orca
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: orcaeventos-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  dbdata:
