name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:11.3
        env:
          MARIADB_DATABASE: orcaeventos
          MARIADB_USER: orca
          MARIADB_PASSWORD: secret
          MARIADB_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, pdo_mysql, gd, redis

      - name: Install Composer dependencies
        run: cd backend && composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy .env
        run: cd backend && cp .env.example .env

      - name: Generate key
        run: cd backend && php artisan key:generate

      - name: Run migrations
        run: cd backend && php artisan migrate --force

      - name: Run tests
        run: cd backend && php artisan test
